name: Deploy Point

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        working-directory: ./src

      - name: Set Nova credentials
        run: echo "COMPOSER_AUTH={\"http-basic\": {\"nova.laravel.com\": {\"username\": \"${{ secrets.NOVA_USERNAME }}\", \"password\": \"${{ secrets.NOVA_LICENSE_KEY }}\"}}}" >> $GITHUB_ENV

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: src/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        working-directory: ./src

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build --if-present

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/node_modules/**
            **/storage/**
            **/tests/**
            .env
          localDir: src
